### PR TITLE
Edit user roles

### PR DESCRIPTION
**Pull request by duskobogdanovski**
Fixes #

#18 

### Proposed fixes:

Now organization member 'editor' is not able to create or edit datasets to public.

### Features:

- [ ] includes tests covering changes
- [ ] includes updated documentation
- [X] includes user-visible changes
- [X] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by duskobogdanovski** [comment]
Yes, it is ready.

**Comment by riccardoerra** [comment]
Tested and all good.
Is there a way to disable the private/public dropdown when adding/editing a dataset so an editor cannot try to make a dataset public and therefore we don't show the error page?

> 403 Forbidden
> Access was denied to this resource.
> Unauthorized to read package <built-in function id>

**Comment by duskobogdanovski** [comment]
On edit dataset if user is 'editor' it should be hidden, in create new it is not because we don't know which org will the user choose but it is handled in the backend if it is editor for the selected organization the dataset will be automatically private. You are saying that on edit dataset the dropdown is visible?

**Comment by riccardoerra** [comment]
editor

**Comment by duskobogdanovski** [comment]
yes it is shown, but strange because works for me, this is the check https://github.com/smallmedia/iod-ckan/pull/33/files/9c1d42f7e80125dfc5dff256d5f055141cdc877c#diff-9fb37c96aa382c0b3b54030952d46360R89

**Comment by duskobogdanovski** [comment]
Ah, i know what is the issue, i guess this template is overwritten in some of the other extensions which i don't have enabled on my side.

**Comment by duskobogdanovski** [comment]
I will need to apply the fix in that extension.

**Pull request merged**
